name: flutter_seekbar
description: A new flutter plugin project.
version: 0.0.3
author: liucheng <liu520vr@gmail.com>
homepage: https://github.com/LiuC520/flutter_seekbar
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutterseekbar
    pluginClass: FlutterSeekbarPlugin
